theme: jekyll-theme-midnight
title: Bitwuzla
description: An SMT solver for bit-vectors, floating-points,
  arrays and uninterpreted functions.
exclude: [tags]
show_downloads: true
collections:
  papers:
    output: true
    permalink: /papers/:name
  awards:
    output: true
    permalink: /awards/:name
